version: '3.9'
services:
  cart-service:
    image: tomerge2/cart-service:latest
    ports:
      - "8080:8080" # Expose cart-service on localhost:8080
    environment:
      - SPRING_RABBITMQ_HOST=rabbitmq
      - SPRING_RABBITMQ_PORT=5672
    depends_on:
      rabbitmq:
        condition: service_healthy # Wait for RabbitMQ to be healthy
    networks:
      - shared-network

  rabbitmq:
    image: rabbitmq:3-management
    ports:
      - "5672:5672"    # AMQP port
      - "15672:15672"  # Management UI port
    environment:
      - RABBITMQ_DEFAULT_USER=guest
      - RABBITMQ_DEFAULT_PASS=guest
    healthcheck:
      test: ["CMD", "rabbitmqctl", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - shared-network

networks:
  shared-network:
    name: shared-network # Shared external network
    driver: bridge
